### ISSUE TITLE
User can see a list of most recent posts

### ISSUE THREAD

**Issue by chang-yoo** [chang-yoo/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can see a list of most recent posts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can see posts that are recently uploaded from sellers with an image and brief description of it.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/99840727/171067821-dee5f7b6-e3b6-4dfc-a72b-32061abc5fda.png">
<img width="177" alt="image" src="https://user-images.githubusercontent.com/99840727/171067840-2fa30b32-c8f4-4856-bae7-cff86dbc516a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` with sql table schema generated from DbDesigner
- [x] Update 6 tables in database 
- [x] Update `data.sql` with four random descriptions for dummy posts purpose

### ☁️ Server

- [x] Add express.js to `server/index.js` and assign as function to a variable
- [x] console log 'running on port" when port is running.
- [x] use get method to pull the dummy data from backend
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for dummy posts 
- [x] Update component to be structured 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
