### ISSUE TITLE
User can move the post to completed page once transaction is finished

### ISSUE THREAD

**Issue by chang-yoo** [chang-yoo/final-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can move the post to completed page once transaction is finished
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the transaction is closed, seller can move the post to history page where other users can see how many histories that the seller have. Also, the review is required so next buyer/seller gets to know if they are scammed or not.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/99840727/171070396-5b519857-9e68-49cc-bb14-ce812d05db91.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/99840727/171070386-411bfbe4-d1e8-455c-b37c-29ccda9cc902.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` by creating sql get that changes status column in post table to closed
- [x] create another sql that changes status to open when user cancels the request (no button)
- [x] create another sql that selects post* with status closed (confirm button)
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a page where user can see their completed history
- [x] change the link of completed page in menu to actual history page.
- [x] add history component in renderpage method of app.jsx

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
