### ISSUE TITLE
User can see details of a post when click it

### ISSUE THREAD

**Issue by chang-yoo** [chang-yoo/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see details of a post when click it

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users are able to take a look at deeper description that is provided from the seller such as detailed description of an item.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/99840727/171068003-d8fee809-1dad-4d12-8f80-64d018b27eb4.png">
<img width="142" alt="image" src="https://user-images.githubusercontent.com/99840727/171068015-f3cedbb0-4e26-4ab4-b5dd-1a8c8c3579e0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] retrieve detailed description from database using get method for specific postId

### ☁️ Server

- [x] include postId to req.params
- [x] test if data is successfully retrieved with specific postId

### ⚡ Client

- [x] hide homepage and construct a structure for detail description
- [x] create a hash for window.location and render page based on it.
- [x] add event listener to each post
- [x] create if statement to match the postId to get the description of that postId 
- [x] retrieve the data from database and put the data to structured template.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
