### ISSUE TITLE
User can search posts

### ISSUE THREAD

**Issue by chang-yoo** [chang-yoo/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the posts that server has found so users can find their specific item by inputting the name of item
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users get to search a name of item that they are specifically looking for. The application will show if the name watches to input values.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="819" alt="image" src="https://user-images.githubusercontent.com/99840727/171068305-b8d2ea78-7daa-40b7-9dc2-9990000c14f3.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/99840727/171068398-3da299f8-9e85-49dd-86c1-ba3a31540772.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` with different values for title for dummy posts to test out the searching bar

### ☁️ Server

- [x] retrieve the data from post table to get the post title for searching
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a form react element for searching bar 
- [x] structure as searching bar and add cancel icon when the value's length is more than 1
- [x] add submit button that listens for searching when value is submitted
- [x] make sure that users can see related post from searching
- [x] the text in post body changes to show what the user is searching for
- [x] throws an cannot find message when the keyword doesn't exist in database

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
