### ISSUE TITLE
User gets navigated to sign in page

### ISSUE THREAD

**Issue by chang-yoo** [chang-yoo/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can get navigated to sign in page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If the user wants to log into their account, the application links to the sign in page so users can log in.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="446" alt="image" src="https://user-images.githubusercontent.com/99840727/171068961-7f8ee2df-56e9-4be1-9852-70dfd9f6a958.png">
<img width="338" alt="image" src="https://user-images.githubusercontent.com/99840727/171068965-d76ee3db-f9b8-4061-b208-f646f424c0bd.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a menu icon that comes out sliding from right when clicked
- [x] create <a> sign in link that navigates to sign in page
- [x] <a> triggers window.location.hash to 'sigin-in'
- [x] renderpage method listens for update in hash location.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
