### ISSUE TITLE
User can log into their account

### ISSUE THREAD

**Issue by chang-yoo** [chang-yoo/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Once the user created account in previous feature, they now can log into their own account and enjoy the features of app.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user successfully creates an account or already has an account, the user just need to write down correct password so the application verifies it and log them into their account once they are correct.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/99840727/171069136-0fc9fd4a-4da0-4d65-b0af-b1de151e51da.png">
<img width="306" alt="image" src="https://user-images.githubusercontent.com/99840727/171069144-4cdce3a7-a273-4528-8cc7-ddd009208dad.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` (when the route changes to sign-in, use argon2.verify to match the password
- [x] if they match, create a payload that contains usreid and username and create a token and send back as response to server
- [ ] 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to verify if the hashedpassword and inputted password match
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
